doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/user'
                prefix: 'Kcalculator\Domain\User\Entity'
            Product:
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/product'
                prefix: 'Kcalculator\Domain\Product\Entity'
            Preference:
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/preference'
                prefix: 'Kcalculator\Domain\Preference\Entity'
            Entry:
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/entry'
                prefix: 'Kcalculator\Domain\Entry\Entity'
            WeightHistory:
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/weight_history'
                prefix: 'Kcalculator\Domain\WeightHistory\Entity'