doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'Kcalculator\Domain\User\Entity'
                alias: Kcalculator
            Product:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'Kcalculator\Domain\Product\Entity'
                alias: Kcalculator
            Preference:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'Kcalculator\Domain\Preference\Entity'
                alias: Kcalculator
            Entry:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'Kcalculator\Domain\Entry\Entity'
                alias: Kcalculator
            WeightHistory:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'Kcalculator\Domain\WeightHistory\Entity'
                alias: Kcalculator