version: '3.8'
services:
  db:
    image: mariadb:10.5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_LOGIN: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kcalculator
    volumes:
      - db-data:/var/lib/mysql:rw
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/kcalculator:delegated
    links:
      - db
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/kcalculator"
      APP_URL: "http://kcalculator.local:8099"
      APP_ENV: "dev"
      APP_SECRET: "053334683d7021094405b2aefb682d27"
      APP_HOSTNAME: "kcalculator.local"
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
  nginx:
    image: nginx:1.19
    ports:
      - "8099:80"
    volumes:
      - .:/var/www/kcalculator:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
  encore:
    image: node:12.13-alpine
    volumes:
      - .:/app
    ports:
      - "${DEV_SERVER_PORT:-8080}:8080"
    working_dir: /app
    command: [ "yarn", "dev-server", "--host=0.0.0.0" ]
volumes:
  db-data: