version: '3.8'
services:
  db:
    image: postgres:13.2
    ports:
      - 5449:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=kcalculator
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  php:
    build:
      ./docker/php
    volumes:
      - .:/var/www/kcalculator:delegated
    links:
      - db
      # - mailer
    environment:
      DATABASE_URL: "postgresql://root:root@db:5432/kcalculator?serverVersion=13.2"
      APP_URL: "http://localhost:8099"
      APP_ENV: "dev"
      APP_SECRET: "ndu5tb2ald1bt3i2279888xdia13le4b"
  nginx:
    image: nginx:1.19
    ports:
      - "8099:80"
    volumes:
      - .:/var/www/kcalculator:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
  encore:
    image: node:10-alpine
    volumes:
      - .:/app
    ports:
      - "${DEV_SERVER_PORT:-8080}:8080"
    working_dir: /app
    command: [ "yarn", "dev-server", "--host=0.0.0.0" ]
volumes:
  db-data: