parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kcalculator\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    Kcalculator\Application\Controller\:
        resource: '../src/Application/Controller/'
        tags: ['controller.service_arguments']

    console_command.csv_import:
        class: Kcalculator\Domain\Product\Command\CsvImportCommand
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: console.command }

